# Generated by Django 2.2.4 on 2019-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipient_mail', models.EmailField(max_length=254, unique=True)),
                ('host_mail', models.EmailField(max_length=254, unique=True)),
                ('host_smtpaddress', models.CharField(max_length=25)),
                ('host_mail_encry_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AlertMail',
        ),
    ]
