# Generated by Django 2.2.4 on 2019-09-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190919_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertmailmodel',
            old_name='host_mail_encry_password',
            new_name='mail_host_password',
        ),
    ]
