# Generated by Django 2.1.1 on 2019-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190919_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmailmodel',
            name='use_tls',
            field=models.BooleanField(default=False),
        ),
    ]
