# Generated by Django 2.1.1 on 2019-10-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alertmailmodel_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmailmodel',
            name='host_mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alertmailmodel',
            name='receipient_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
